### ISSUE TITLE
Handle changes in array_init for PHP 7.3

### ISSUE THREAD

**Issue by ejn** [dvzgeo/php_ogr#7]
Attempting to compile with PHP 7.3 leads to errors due to [changes in array_init](https://github.com/php/php-src/blob/PHP-7.3.1/UPGRADING.INTERNALS#L44).

Output from make:
```
/bin/bash /home/ejn/php_ogr/libtool --mode=compile cc  -I. -I/home/ejn/php_ogr -DPHP_ATOM_INC -I/home/ejn/php_ogr/include -I/home/ejn/php_ogr/main -I/home/ejn/php_ogr -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/usr/include/gdal  -DHAVE_CONFIG_H  -g -O2   -c /home/ejn/php_ogr/ogr.c -o ogr.lo
libtool: compile:  cc -I. -I/home/ejn/php_ogr -DPHP_ATOM_INC -I/home/ejn/php_ogr/include -I/home/ejn/php_ogr/main -I/home/ejn/php_ogr -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/usr/include/gdal -DHAVE_CONFIG_H -g -O2 -c /home/ejn/php_ogr/ogr.c  -fPIC -DPIC -o .libs/ogr.o
In file included from /usr/include/php/20180731/Zend/zend.h:27:0,
                 from /usr/include/php/20180731/main/php.h:34,
                 from /home/ejn/php_ogr/ogr.c:42:
/home/ejn/php_ogr/ogr.c: In function 'zif_ogr_f_getfieldasintegerlist':
/usr/include/php/20180731/Zend/zend_types.h:792:24: error: expected expression before 'do'
 #define ZVAL_ARR(z, a) do {      \
                        ^
/usr/include/php/20180731/Zend/zend_API.h:377:28: note: in expansion of macro 'ZVAL_ARR'
 #define array_init(arg)    ZVAL_ARR((arg), zend_new_array(0))
                            ^~~~~~~~
/home/ejn/php_ogr/ogr.c:2983:6: note: in expansion of macro 'array_init'
  if (array_init(return_value) == FAILURE)
      ^~~~~~~~~~
/home/ejn/php_ogr/ogr.c: In function 'zif_ogr_f_getfieldasdoublelist':
/usr/include/php/20180731/Zend/zend_types.h:792:24: error: expected expression before 'do'
 #define ZVAL_ARR(z, a) do {      \
                        ^
/usr/include/php/20180731/Zend/zend_API.h:377:28: note: in expansion of macro 'ZVAL_ARR'
 #define array_init(arg)    ZVAL_ARR((arg), zend_new_array(0))
                            ^~~~~~~~
/home/ejn/php_ogr/ogr.c:3031:6: note: in expansion of macro 'array_init'
  if (array_init(return_value) == FAILURE)
      ^~~~~~~~~~
/home/ejn/php_ogr/ogr.c: In function 'zif_ogr_f_getfieldasstringlist':
/usr/include/php/20180731/Zend/zend_types.h:792:24: error: expected expression before 'do'
 #define ZVAL_ARR(z, a) do {      \
                        ^
/usr/include/php/20180731/Zend/zend_API.h:377:28: note: in expansion of macro 'ZVAL_ARR'
 #define array_init(arg)    ZVAL_ARR((arg), zend_new_array(0))
                            ^~~~~~~~
/home/ejn/php_ogr/ogr.c:3086:6: note: in expansion of macro 'array_init'
  if (array_init(return_value) == FAILURE)
      ^~~~~~~~~~
Makefile:196: recipe for target 'ogr.lo' failed
make: *** [ogr.lo] Error 1
```
